# application-k6.yml
spring:
  datasource:
    url: jdbc:mysql://mysql-k6:3306/webty_k6_db
    username: k6_user
    password: k6_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:webty-k6-redis}
      port: ${REDIS_PORT:6379}